"""Criando tabela CartaoCredito e Lancamentos

Revision ID: 777207d8e90e
Revises: 
Create Date: 2024-01-18 23:36:51.196940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777207d8e90e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartao_credito',
    sa.Column('ID_Cartao', sa.Integer(), nullable=False),
    sa.Column('NM_Cartao', sa.String(length=50), nullable=False),
    sa.Column('Bandeira', sa.String(length=50), nullable=False),
    sa.Column('Limite_Disponivel', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('ID_Cartao')
    )
    op.create_table('lancamento',
    sa.Column('ID_Lancamento', sa.Integer(), nullable=False),
    sa.Column('ID_Cartao', sa.Integer(), nullable=True),
    sa.Column('NM_Local_Compra', sa.String(length=50), nullable=False),
    sa.Column('TP_Compra', sa.String(length=15), nullable=False),
    sa.Column('TP_Produto', sa.String(length=20), nullable=False),
    sa.Column('VL_Compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('NO_Parcela_Atual', sa.Integer(), nullable=False),
    sa.Column('NO_Parcela_Final', sa.Integer(), nullable=False),
    sa.Column('DT_Compra', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Cartao'], ['cartao_credito.ID_Cartao'], ),
    sa.PrimaryKeyConstraint('ID_Lancamento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lancamento')
    op.drop_table('cartao_credito')
    # ### end Alembic commands ###
